"""Public Provider SDK surface for third-party and built-in providers."""

from __future__ import annotations

from governance.providers.capabilities import (
    SUPPORTED_CAPABILITIES,
    CapabilityId,
)
from governance.providers.contracts import (
    PROVIDER_ENTRY_POINT_GROUP,
    PROVIDER_SDK_API_VERSION,
    AuthorizedMutationCapability,
    CapabilityBinding,
    CapabilityFactory,
    CompatibilityPreflightCapability,
    GovernanceGraphCapability,
    LineageCapability,
    MetadataDiscoveryCapability,
    PropertyObservationsCapability,
    ProviderConfigValidator,
    ProviderDescriptor,
    ProviderRegistration,
    ProviderRuntimeContext,
    RemoteStateReadCapability,
    TargetPlanningCapability,
)
from governance.providers.discovery import discover_providers
from governance.providers.errors import (
    CODE_BROKEN_ENTRY_POINT,
    CODE_DISCOVERY_FAILED,
    CODE_DUPLICATE_PROVIDER_ID,
    CODE_INCOMPATIBLE_SDK,
    CODE_INVALID_CAPABILITY_BINDING,
    CODE_INVALID_CONFIG_VALIDATOR,
    CODE_INVALID_DESCRIPTOR,
    CODE_INVALID_PROVIDER_ID,
    CODE_INVALID_PROVIDER_VERSION,
    CODE_INVALID_SDK_COMPATIBILITY,
    CODE_MISSING_CAPABILITY,
    CODE_UNKNOWN_CAPABILITY,
    CODE_UNKNOWN_PROVIDER,
    ProviderDescriptorError,
    ProviderDiagnostic,
    ProviderDiscoveryError,
    ProviderError,
    ProviderRegistrationError,
    ProviderRegistryError,
)
from governance.providers.registry import ProviderRegistry

__all__ = [
    "PROVIDER_ENTRY_POINT_GROUP",
    "PROVIDER_SDK_API_VERSION",
    "SUPPORTED_CAPABILITIES",
    "AuthorizedMutationCapability",
    "CODE_BROKEN_ENTRY_POINT",
    "CODE_DISCOVERY_FAILED",
    "CODE_DUPLICATE_PROVIDER_ID",
    "CODE_INCOMPATIBLE_SDK",
    "CODE_INVALID_CAPABILITY_BINDING",
    "CODE_INVALID_CONFIG_VALIDATOR",
    "CODE_INVALID_DESCRIPTOR",
    "CODE_INVALID_PROVIDER_ID",
    "CODE_INVALID_PROVIDER_VERSION",
    "CODE_INVALID_SDK_COMPATIBILITY",
    "CODE_MISSING_CAPABILITY",
    "CODE_UNKNOWN_CAPABILITY",
    "CODE_UNKNOWN_PROVIDER",
    "CapabilityBinding",
    "CapabilityFactory",
    "CapabilityId",
    "CompatibilityPreflightCapability",
    "GovernanceGraphCapability",
    "LineageCapability",
    "MetadataDiscoveryCapability",
    "PropertyObservationsCapability",
    "ProviderConfigValidator",
    "ProviderDescriptor",
    "ProviderDescriptorError",
    "ProviderDiagnostic",
    "ProviderDiscoveryError",
    "ProviderError",
    "ProviderRegistration",
    "ProviderRegistrationError",
    "ProviderRegistry",
    "ProviderRegistryError",
    "ProviderRuntimeContext",
    "RemoteStateReadCapability",
    "TargetPlanningCapability",
    "discover_providers",
]
